// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcSrvClient is the client API for GrpcSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcSrvClient interface {
	GetData(ctx context.Context, in *GetDataReq, opts ...grpc.CallOption) (*GetDataResp, error)
}

type grpcSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcSrvClient(cc grpc.ClientConnInterface) GrpcSrvClient {
	return &grpcSrvClient{cc}
}

func (c *grpcSrvClient) GetData(ctx context.Context, in *GetDataReq, opts ...grpc.CallOption) (*GetDataResp, error) {
	out := new(GetDataResp)
	err := c.cc.Invoke(ctx, "/GrpcSrv/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcSrvServer is the server API for GrpcSrv service.
// All implementations must embed UnimplementedGrpcSrvServer
// for forward compatibility
type GrpcSrvServer interface {
	GetData(context.Context, *GetDataReq) (*GetDataResp, error)
	mustEmbedUnimplementedGrpcSrvServer()
}

// UnimplementedGrpcSrvServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcSrvServer struct {
}

func (UnimplementedGrpcSrvServer) GetData(context.Context, *GetDataReq) (*GetDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedGrpcSrvServer) mustEmbedUnimplementedGrpcSrvServer() {}

// UnsafeGrpcSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcSrvServer will
// result in compilation errors.
type UnsafeGrpcSrvServer interface {
	mustEmbedUnimplementedGrpcSrvServer()
}

func RegisterGrpcSrvServer(s grpc.ServiceRegistrar, srv GrpcSrvServer) {
	s.RegisterService(&GrpcSrv_ServiceDesc, srv)
}

func _GrpcSrv_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcSrvServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcSrv/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcSrvServer).GetData(ctx, req.(*GetDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcSrv_ServiceDesc is the grpc.ServiceDesc for GrpcSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcSrv",
	HandlerType: (*GrpcSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _GrpcSrv_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
